export const extractorPrompt = `Extract only explicitly stated or confirmed fields from the user's Indonesian message.
Do not infer final values from weak hints.
Do not extract questions like aku belum mengerti, maksudnya gimana, contoh apa, or user confusion as data.
If the user asks a question only, return empty patches.
If the user asks for a recommendation, return pendingSuggestions, not final patches.
If the user confirms a previous pending suggestion, return confirmedPendingFields.
Extract every explicit field in the message, even when several fields appear in one sentence.
If the user corrects a value, emit a new patch for the corrected field. Example: "bukan marketing, public speaking" means the relevant expertise/focus value is public speaking.

Use these canonical field keys:
- Trainer flow brainstorming core fields: trainer_name, institution, expertise, audience, outcome.
- Trainer flow brainstorming optional fields: activities, training_objective, training_date.
- Trainer flow training_details fields are generated by the system unless explicitly stated: program_name, delivery_method, duration_jp.
- Master flow profile core fields: trainer_name, organization_name, organization_focus, target_participants, industry_problem, program_goal, training_location, training_duration.
- Master flow generated fields: program_name, organization_city.
- Unit selection fields (both flows): selected_unit_code (phaseKey: unit_selection). Extract this when the user explicitly states a SKKNI unit code like "N.79JPW00.140.1" or says they want to use a specific unit. The value must be the exact unit code string.

Do not extract WSP / SKKNI unit detail, competency elements, KUK, assessment guide, or competency map from chat. Those must come from WSP endpoints after the user selects a unit code.
Return structured output matching the provided schema.`
